### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by Jay-study-nildana**
updated readme with some additional notes, if it helps.

### CODE REVIEW

**Comment by Jay-study-nildana** [comment]
It's a tiny little but I was almost about to run the EF table script until i realized its no longer required. other developers might also get confused like i did. 

Meanwhile, this repo is great. Helped me get past a crucial mysql situation. Thanks.

**Comment by jasonsturges** [comment]
@Jay-study-nildana Hi, thanks for the message and pull request.

.NET Core has finally fixed this in 3.1.9?  Are you using MySQL Entity Framework Core 8.0.20?

Think I'd shift this around a bit to lead with the statement that it's not necessary; but then, leave a note for earlier versions that includes the instructions.  

Or maybe something like:

> ### Create Entity Framework Migration Table in MySQL
>
> Prior to .NET Core 3.1.9, Running the `dotnet ef` fails ... executing the following SQL script. 
> ```
> use mydatabase;
> ...
>

Or maybe this needs a troubleshooting section at the bottom for legacy issues...

I'll get my environment updated and check it out.  Thanks again for the note.

**Comment by Jay-study-nildana** [comment]
@jasonsturges 

you are most welcome. MS suggests pomelo.

here is the package info from a quick demo app i built last week. 

    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.9" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.2.4" />   
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.9" />  
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference> 

In case you wish to see, the full code is here. 

https://github.com/Jay-study-nildana/CSharpForStudents/tree/main/crudaspnetcore3point1mysql

I cannot comment on the mysql 8.0 (I did not have to use it) but I can confirm the 3.1.9 on the MS side of the things. They seem to have fixed it. 

However, you wish to update your readme, I am cool :) I spent a few minutes wondering why I have to do it until i realized it was fixed. as long we get this visible for future developers, i am good.

**Comment by Jay-study-nildana** [comment]
Oh wait, I just realized, 8.0, you are talking about the mysql database version. Ah! Okay. Yes, I tested this against 8.0 MySQL server running locally.

**Comment by jasonsturges** [comment]
@Jay-study-nildana Ah, I see.  Yeah, Pomelo has always worked.

Here, I'm using MySQL's adapter:

```csproj
  <ItemGroup>
    <PackageReference Include="MySql.Data.EntityFrameworkCore" Version="8.0.20" />
  </ItemGroup>
```

Been years this hasn't worked - unfortunate...

**Comment by Jay-study-nildana** [comment]
@jasonsturges 

Yeah, MS has stopped recommending that on their official docs. I remember using the Mysql package you are using using a long time ago, and when I wanted to do EF Core this time, I was confused with this Pomelo, something. Yeah, I think, work has stopped on that Mysql thing, and MS is now asking people to use Pomelo entirely. 

Let me know if you want me to update this pull request with the pomelo setup in the project package. Or, close this if you wish to keep it as it is.

**Comment by jasonsturges** [comment]
@Jay-study-nildana Official MySQL Connector is actively developed, with Connector 8.0.20 built for Entity Framework Core 3.1.1 on .NET Standard 2.0.

There's a history of frustration, where many reverted to Pomelo - this repository kept a Pomelo recommendation for years.

While there are alternatives to Oracle's connectors such as Pomelo, a major point of this scaffolding is to retain the MySQL Connector to a MySQL database.

Thanks, though.  Best.

**Pull request closed without merging**
